### ISSUE TITLE
command to create skeleton for a new dataset

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#1]
Possibly with (options?) for
- `setup.py`, thus creating an "installable" dataset
- metadata via `metadata.json`
- integration with travis-ci

**Comment by LinguList** [comment]
Ah, yes, when working on datasets in the past, it was clear that a bit more might be needed for pylexibank: https://github.com/lexibank/pylexibank/issues/112

In fact, one could make some kind of a form that could be filled out (or passed as arguments), like: name of folder, name of dataset, reference (if already available, imagine pulling it from glottolog), etc., all things that would make this much faster.

**Comment by xrotwang** [comment]
I find it somewhat difficult to draw the line between what's generally useful (e.g. for `StructureDataset`s like https://github.com/cldf-datasets/szetosinitic) and what's lexibank specific.
Right now I'm leaning towards erring on the side of comprehensiveness, i.e. create `.travis.yml` etc. by default, considering that these files can always simply be deleted if unwanted.

**Comment by xrotwang** [comment]
The only thing where I'm hesitant is `metadata.json`. Having such a file lying around may create confusion if it's not really used and there are `README.md`, and maybe `.zenodo.json` around as well. So, `metadata.json` makes too much of an assumption about the particular processing workflow, and hence curation model of a dataset to be generally useful.

**Comment by LinguList** [comment]
Yes, given the abundance of feature data, it is definitely not always clear how to handle this. Especially, I guess, however, also as long as we are short of datasets that might expose the potential complexities...

**Comment by xrotwang** [comment]
That's true. So to make this work, I'll try to make `cldfbench` and `pylexibank` compatible as soon as possible, so that new functionality can be piloted in `lexibank`, and if it's generic enough, be ported to `cldfbench` as second step.

**Comment by LinguList** [comment]
And once I've a bit more time, I can provide more examples for cldfbench datasets. E.g., I'd also like to provide distance matrices between languages, as reported in some studies on mutual intelligiblity (eg [here](https://github.com/digling/cddb/blob/master/datasets/Tang2007/raw/Tang2007-table-a2.csv)), or even phylogenetic trees. Here, one could, in principle, even discuss some of these structures in cldfbench before and later port to lexibank, as lexical data does not usually require a tree, while trees are published often anyway...
