### ISSUE TITLE
Have the `new` command add a proper .gitignore

### ISSUE THREAD

**Issue by tresoldi** [cldf/cldfbench#13]
It would be helpful to have a proper `.gitignore` file in the template, so that the `new` command carries it to new datasets. It would suffice for it to be a standard Python `.gitignore` with any extra Lexibank/CLDF specific stuff (such as `cldf/.transcription-report.json`).

**Comment by xrotwang** [comment]
I'm a bit hesitant - having been bitten by too inclusive `.gitignore`s. OTOH, I think `git add`ing all files is the default of GitHub desktop - which may lead to bad things without a `.gitignore` ... Hm. Are there generally useful rules for this - can you propose one, @tresoldi ?

**Comment by tresoldi** [comment]
@xrotwang for now, I've just been using GitHub's default one for Python, excluding the transcription report as well (in the first line: https://github.com/lexibank/northeuralex/blob/master/.gitignore). It is good enough, as it also takes care of virtual enviroments, pycache, etc.

**Comment by xrotwang** [comment]
I'll add one for the `lexibank_simple` template. Leaving this issue open until we fix it for `cldfbench` as well.
