### ISSUE TITLE
Clone catalogs with --depth=1?

### ISSUE THREAD

**Issue by Anaphory** [cldf/cldfbench#14]
The history of the reference catalogues might be long and not always useful, would it make sense to – optionally or as changeable default – clone the catalogue data repositories only with `--depth=1`?

**Comment by xrotwang** [comment]
Hm. Not necessarily. Note that `cldfbench catinfo` lists all available tags, and it might be required to checkout an old release tag to reproduce some result. So I'd say cloning with a specific depth is an expert operation, for people who understand the trade-off - not a useful default. It may be worth documenting this somewhere - possibly for the `glottolog/glottolog` repos, where a smaller repository size may have a real impact.
