### ISSUE TITLE
Incompatibility with Python3.5 due to dependency

### ISSUE THREAD

**Issue by tresoldi** [cldf/cldfbench#18]
Due to new releases of `openpyxl` (the library for reading Excel files) using the `f-string` notation introduced with 3.6 ([here](https://www.python.org/dev/peps/pep-0498/)), `cldfbench` is not running under 3.5 anymore. `python_requires` is [currently](https://github.com/cldf/cldfbench/blob/f373855e3b9cde029578e77c26136f0df26a82fa/setup.py#L25) set as `>=3.5` and `openpyxl` [is a dependency](https://github.com/cldf/cldfbench/blob/f373855e3b9cde029578e77c26136f0df26a82fa/setup.py#L47).

The `f-notation` is now used in multiple places (one example, [here](https://bitbucket.org/openpyxl/openpyxl/src/31472e215b079ec2f846ec109ae88ca01100a992/openpyxl/worksheet/worksheet.py#lines-392)) and even importing fails:

```
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openpyxl
Traceback (most recent call last):
[...]
  File "/home/tresoldi/src/phylogenetics-data-management-tutorial/env/lib/python3.5/site-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
```

The easiest and uglier solution would be to pin the dependency to version `3.0.0`. Non-easy solutions might involve replacing the dependency.

**Comment by xrotwang** [comment]
Hm. Requiring a better python version with just a bugfix release seems bad style to me. But anyway, yes, I guess pinning (at least conditioned on `python_version`) is the thing to do here.
