### ISSUE TITLE
CLDF Bench fails to register more than one subcommand

### ISSUE THREAD

**Issue by LinguList** [cldf/cldfbench#25]
I have a strange behavior. `cldfbench` lists the following specific commands:

```
    hsiuhmongmien.structure
                        Check for consistency in the structure.
    chindialectsurvey.structure
                        Check for consistency in the structure.
```

Yet, the chindialectsurvey does not have this command, it has only the command "cognates". 

When I then install normansinitic, I get:

```
    hsiuhmongmien.structure
                        Check for consistency in the structure.
    chindialectsurvey.structure
                        Check for consistency in the structure.
    normansinitic.structure
                        Check for consistency in the structure.
```

So it seems that commands are in fact registered, but the default of the subcommand that one installs the first time is taken as the one to go with (and it is also called):

```
$ cldfbench normansinitic.structure
Traceback (most recent call last):
  File "...lexi4/bin/cldfbench", line 11, in <module>
    load_entry_point('cldfbench', 'console_scripts', 'cldfbench')()
  File "...cldf/cldfbench/src/cldfbench/__main__.py", line 75, in main
    return args.main(args) or 0
  File ".../data/datasets/lexibank-new/hsiuhmongmien/commands/structure.py", line 18, in run
    wl = Wordlist.from_cldf(str(ds.cldf_specs()[None].metadata_path))
TypeError: 'CLDFSpec' object is not subscriptable

```

**Comment by xrotwang** [comment]
Just this week I noticed the same thing. It only happens with dataset-specific subcommands, i.e. when the `commands` package isn't wrapped in a namespace package. So I guess it's because two datasets want to register the same package name `commands`. I managed to circumvent the problem by using a custom name `walscommands` for the package. But will investigate further.

**Comment by xrotwang** [comment]
Ah yes, that's surely the problem. When trying to load the second entry point, `commands` isn't actually imported, but looked up in `sys.modules`.

**Comment by LinguList** [comment]
Okay, this means I will for now register a custom command name for the dataset, following your suggestion.

**Comment by xrotwang** [comment]
I'm not sure what the best solution would be, but I only see two options:
- turning the dataset into a package `cldfbench_<datasetid>` with the code in `__init__.py`,
- or recommending uniquely named commands packages.

The latter is probably simpler, and also backwards compatible.

**Comment by xrotwang** [comment]
@LinguList It's not the command name that needs to be unique, it's the python package name! I.e. you must rename `commands/` to `<uniqueprefix>commands/` or similar.

**Comment by LinguList** [comment]
Okay. Thanks for clarifying. I'll use the dataset ID for the package now.

**Comment by xrotwang** [comment]
Adapted docs: https://github.com/cldf/cldfbench/blob/master/src/cldfbench/commands/README.md#dataset-specific-commands
