### ISSUE TITLE
requirements.txt on Windows with additional newlines

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldfbench#26]
A very minor issue:

`requirements.txt` in `cldf/` looks like this when `cldfbench` (and related) are run on Windows platforms:

```
appdirs==1.4.3

atomicwrites==1.3.0

certifi==2019.11.28

chardet==3.0.4
```

Theoretically, the call to `write_text()` [here](https://github.com/cldf/cldfbench/blob/f373855e3b9cde029578e77c26136f0df26a82fa/src/cldfbench/cldf.py#L91) would either need `newline=""` passed to the `pathlib` call or the additional `\n` during the writing needs to be ignored for Windows platforms. Both annoying and I'm not sure whether its worth the hassle?

**Comment by xrotwang** [comment]
Maybe this can be fixed as well with config in `.gitattributes`? We already have this for `*.csv`, seee.g. https://github.com/cldf-datasets/normansinitic/blob/master/cldf/.gitattributes

**Comment by chrzyki** [comment]
As far as I can tell (assuming I'm using this correctly) this doesn't help: there is a new line and a Windows `\r\n` additionally, hence the empty lines. However, I'll play around with this a little bit more to figure out if this is an issue on my end.

**Comment by xrotwang** [comment]
Since `git diff --ignore-blank-lines` is enough to hide this difference, I don't consider this a real issue.
