### ISSUE TITLE
Add cldfdiff command

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#29]
Since buildbot runs `makecldf` before checking the resulting CLDF dataset, the content that is checked may differ from `HEAD` in the data repository. So to decide whether a dataset can be released **as is** or if it needs to be re-generated, a `cldfbench cldfdiff` command would be useful returning
- 0 if no essential changes to the CLDF can be detected
- 2 otherwise

where "essential changes to the CLDF" are
- any changes in `*.csv` or `*.bib` files
- changes of catalog versions in `*-metadata.json`

i.e. ignoring changes in `requirements.txt` and other metadata changes.

**Comment by xrotwang** [comment]
@SimonGreenhill @chrzyki @LinguList what do you think about this, in particular about the proposed "essential changes"?

**Comment by LinguList** [comment]
I completely agree.

**Comment by SimonGreenhill** [comment]
great idea. `metadata.json` should also be watched in case that gets updated too, right?

Could this be extended in a lexibank context to check for orthography.csv/lexemes.csv?

**Comment by SimonGreenhill** [comment]
also can we just call it 'diff' rather than 'cldfdiff' as `cldfbench diff` is already pretty clear? :)

**Comment by xrotwang** [comment]
Changes in `metadata.json` will end up as changes in `cldf/cldf-metadata.json`, so this is already taken care of.

**Comment by xrotwang** [comment]
Here's output from my current implementation:
```
$ cldfbench cldfdiff lexibank_chenhmongmien.py 
INFO    running diff on chenhmongmien ...
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   cldf/.transcription-report.json
	modified:   cldf/cldf-metadata.json
	modified:   cldf/requirements.txt

no changes added to commit (use "git add" and/or "git commit -a")
WARNING Changed repository version: Glottolog: v4.1-20-gea2ca69206 -> v4.1-34-g15b9b9b
WARNING Changed repository version: Repository: v2.0.1-7-ga3c80fe -> v2.0.1-13-g080174a
WARNING Changed repository version: Concepticon: v2.2.1a-305-g9f25da5 -> v2.2.1a-284-g402c660
INFO    ... done chenhmongmien [0.0 secs]
INFO    ----------------------------------------------------------------------
INFO    Please commit and push changes to GitHub before releasing the dataset!
INFO    ----------------------------------------------------------------------
```

**Comment by xrotwang** [comment]
Again, the rationale of this command is as follows: buildbot will run this at the end of the build process. So, after all tests/checks are passed, this last step is run. If the result is
- OK - no essential changes - the dataset can be released immediately (via GitHub UI)
- WARN (or FAIL?) - essential changes - the cldf must be regenerated locally (with #30 ), commited and pushed before releasing via GitHub UI.
