### ISSUE TITLE
Support for writing multiple CLDF datasets

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#3]
There are use cases which require support for writing multiple CLDF datasets:
- AUTOTYP with its >4mio datapoints would require splitting the dataset into multiple CLDF datasets of the same module.
- Datasets combining typological and lexical data would require writing a `Wordlist` and a `StructureDataset`.

In both cases, the `LanguageTable` would be shared across datasets, thus, it would seem best to simply write multiple `*-metadata.json` dataset descriptions to the `cldf` directory.

Providing a method
```python
    def cldf_writer_from_spec(self, spec)
```
may be all that's necessary for this use case.

**Comment by LinguList** [comment]
I'll try and have a look to provide a first usecase for Sinitic data with structure (sound inventories) and word forms. So far, I have already added [liusinitic](https://github.com/lexibank/liusinitic) in form of lexemes, but would now also add the sound inventories, which I typed off some time before without ever knowing how to actually use them.

**Comment by SimonGreenhill** [comment]
Another example of this is channumerals which has lots of lexemes and `Base` as a structural feature (and maybe a few more).
