### ISSUE TITLE
cldf metadata loading is difficult to debug

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldfbench#32]
cldfbench iterates over all installed datasets and their metadata. I had a metadata.json file with a typo in it (trailing comma), which causes all uses of cldfbench .. and all the rest to choke with a JSONDecode error. This is hard to debug as it does not tell you which JSON file was breaking.

https://github.com/cldf/cldfbench/blob/9c7d04059d76fe08ddf2f8c148ffba3ae89d7d8f/src/cldfbench/metadata.py#L54-L60

One solution would be to wrap the json.load call in a try..except block but I wonder if this is better caught at a higher level?

**Comment by xrotwang** [comment]
Hm, true. Buildbot makes this somewhat better, because there's always just one dataset installed. But I agree that this should already fail in [`iter_datasets`](https://github.com/cldf/cldfbench/blob/9c7d04059d76fe08ddf2f8c148ffba3ae89d7d8f/src/cldfbench/dataset.py#L22-L34).
