### ISSUE TITLE
Support for referencing standard catalogs

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#4]
The library/cli should support making use of standard catalogs, including using particular versions of these.

See also https://github.com/lexibank/pylexibank/issues/78

**Comment by xrotwang** [comment]
@SimonGreenhill @LinguList what about something like this:
```python
>>> from cldfbench.catalogs import Catalog
>>> with Catalog('../glottolog/glottolog', 'v4.0') as glottolog:
...    print(glottolog.describe())
... 
v4.0
>>> print(glottolog.describe())
v4.0-51-gd1fd2f4
```

**Comment by SimonGreenhill** [comment]
That looks sensible. Catalog could be subclassed if necessary to provide catalog specific things.

**Comment by xrotwang** [comment]
@SimonGreenhill yes, the catalog object will have an `api` attribute, which gives access to the appropriate `clldutils.apilib.API` object.

**Comment by xrotwang** [comment]
See #5
