### ISSUE TITLE
cldfbench ci command produces problematic path on Windows platforms

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldfbench#46]
```
$ cldfbench ci lexibank_dataset.py
```

on Windows platforms produces

```
pytest --cldf-metadata=cldf\cldf-metadata.json test.py
```

as a path for the GH actions YAML (instead of `cldf/cldf-metadata...`). The `\` doesn't work with the test environment and results in a file not found error.

Code that's responsible for this:

https://github.com/cldf/cldfbench/blob/8d1d75126879e49a472e5a89ecc9a3397143e388/src/cldfbench/ci.py#L72

Not a huge issue but again an interesting case were path handling is weird on different platforms.

**Comment by xrotwang** [comment]
I think path handling isn't really weird. One just has to be super-aware about what one wants to do - and creating paths for one platform from code running on a different platform is probably the trickiest case. Seems like the equivalent of Unicode and ASCII - when your only language is English, you get away with ignorance :)

**Comment by chrzyki** [comment]
Good point. :)
