### ISSUE TITLE
Support git submodules in raw dir

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldfbench#59]
The scenario of raw data in form of [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in `raw/` should be supported better:
- in `makecldf`, `raw/` should be traversed, adding each repository as provenance,
- a utility function should be available to update all submodules - to be called in a dataset's `cmd_download`.

**Comment by LinguList** [comment]
Ah, yes, I started to work with submodules in `ids/keypano`, and was wondering how to proceed best here, so having something I can adhere to will be useful.
