### ISSUE TITLE
SchemaError in tutorial

### ISSUE THREAD

**Issue by martino-vic** [cldf/cldfbench#73]
Hi, I'm still relatively new to the cldf ecosystem and am currently in the process of familiarising myself with it. So I was going through the cldfbench tutorial and all went well until the last step where I get `SchemaError: 'Dataset has no table "ValueTable"'` on Windows 10. The command I ran was `cldfbench makecldf theid/cldfbench_theid.py --glottolog=C:\Users\Viktor\OneDrive\PhD\lexibank\glottolog --glottolog-version=v4.5` And this is the content of my cldfbench_theid.py:
```
import pathlib

from cldfbench import Dataset as BaseDataset

def cldf_specs(self):
    from cldfbench import CLDFSpec
    return CLDFSpec(dir=self.cldf_dir, module='StructureDataset') 

class Dataset(BaseDataset):
    dir = pathlib.Path(__file__).parent
    id = "theid"

    def cldf_specs(self):  # A dataset must declare all CLDF sets it creates.
        return super().cldf_specs()

    def cmd_download(self, args):
        """
        Download files to the raw/ directory. You can use helpers methods of `self.raw_dir`, e.g.

        >>> self.raw_dir.download(url, fname)
        """
        self.raw_dir.download('https://wals.info/feature/1A.tab', '1A.tsv')

    def cmd_makecldf(self, args):
        """
        Convert the raw data to a CLDF dataset.

        >>> args.writer.objects['LanguageTable'].append(...)
        """

        from csvw.dsv_dialects import Dialect
        for row in self.raw_dir.read_csv(
            '1A.tsv',
            dicts=True, 
            dialect=Dialect(
                skipRows=5,  # Ignore the citation info on top
                skipBlankRows=True,
                delimiter='\t',
            )
        ):
            args.writer.objects['ValueTable'].append({
                'ID': row['wals code'],
                'Language_ID': row['wals code'],
                'Parameter_ID': '1A',
                'Value': row['description'],
            })
```
Could somebody point out what I am doing wrong?

**Comment by chrzyki** [comment]
Hi @martino-vic,

neat to hear that you're playing around with CLDF!

`cldf_specs()` is meant to override the default definition of `cldf_specs` for the `Dataset` class. Hence, your override (or the override provided in the tutorial) has to happen inside of the class. Currently, you're defining it twice, once outside of the class and once inside of the class (which is just the default provided by `cldfbench`). Meaning:

```python
def cldf_specs(self):  # A dataset must declare all CLDF sets it creates.
    from cldfbench import CLDFSpec
    return CLDFSpec(dir=self.cldf_dir, module="StructureDataset")
```

has to be in the `Dataset` class:

```python
class Dataset(BaseDataset):
    dir = pathlib.Path(__file__).parent
    id = "theid"

    def cldf_specs(self):  # A dataset must declare all CLDF sets it creates.
        from cldfbench import CLDFSpec
        return CLDFSpec(dir=self.cldf_dir, module="StructureDataset")
...
```

Hope that helps!

**Comment by martino-vic** [comment]
Ah, thank you for the great support! I implemented these changes now, and it gives me this error:
```
ERROR:
Invalid dataset spec: <cldfbench.dataset> theid/cldfbench_theid.py
```
In fact, it is the same error that I got earlier already [here](https://github.com/martino-vic/streitberggothic/issues/2#issuecomment-1006836711), with my actual dataset, so I guess it's a good step forward being able to reproduce it. Now it would be good to know what causes it. I imagine it must have something to do with my system (Windows 10), or the way I preinstalled some dependencies, if the tutorial version works for others. Just for completeness: I ran the same command as mentioned in the earlier comment and this is how the script looks now: 

````
import pathlib

from cldfbench import Dataset as BaseDataset

class Dataset(BaseDataset):
    dir = pathlib.Path(__file__).parent
    id = "theid"

    def cldf_specs(self):  # A dataset must declare all CLDF sets it creates.
        from cldfbench import CLDFSpec
        return CLDFSpec(dir=self.cldf_dir, module='StructureDataset') 

    def cmd_download(self, args):
        """
        Download files to the raw/ directory. You can use helpers methods of `self.raw_dir`, e.g.

        >>> self.raw_dir.download(url, fname)
        """
        self.raw_dir.download('https://wals.info/feature/1A.tab', '1A.tsv')

    def cmd_makecldf(self, args):
        """
        Convert the raw data to a CLDF dataset.

        >>> args.writer.objects['LanguageTable'].append(...)
        """

        from csvw.dsv_dialects import Dialect
        for row in self.raw_dir.read_csv(
            '1A.tsv',
            dicts=True, 
            dialect=Dialect(
                skipRows=5,  # Ignore the citation info on top
                skipBlankRows=True,
                delimiter='\t',
            )
        ):
            args.writer.objects['ValueTable'].append({
                'ID': row['wals code'],
                'Language_ID': row['wals code'],
                'Parameter_ID': '1A',
                'Value': row['description'],
            })
```

**Comment by chrzyki** [comment]
Interesting! Thanks for the detailed report. I currently don't have a Windows machine available to me but will do so later this evening, then I'll try and replicate the issue. Some small questions:

- What version of Python are you using?
- Could you show me the output of `pip freeze` for the (virtual) environment where you're running `cldfbench`?
- Does anything change if you `cd` directly in the project directory and call `cldfbench` from there? (i.e. `cldfbench makecldf cldfbench_theid.py --glottolog=...` directly in the `theid` directory?)
- Has the rest of the project's skeleton been correctly generated? (In particular check whether the entry points in `setup.py` match your dataset id)

At any rate, I'll try and replicate the issue with my Windows computer later this evening.

**Comment by martino-vic** [comment]
Ok I now it ran. Had to run it from a virtual environment, as it is literally indicated in the tutorial. Sorry about this inattentiveness and thanks for helping me out!
