### ISSUE TITLE
Can't find pip

### ISSUE THREAD

**Issue by SamPassmore** [cldf/cldfbench#80]
Hi Robert, 

This is probably a problem with my installation of cldfbench, but maybe you have come across it before or know of a solution. 

Currently when I run the command:
`./env/bin/python3 ./env/bin/cldfbench lexibank.makecldf --glottolog-version v4.4 --concepticon-version v2.5.0 kinbank`

I get a long error trace, ending with:
`FileNotFoundError: [Errno 2] No such file or directory: 'pip'`

Everything is running within a virtual environment, including pip. That is I can run this with the following result:
```
./env/bin/pip --version
pip 21.2.4 from /Users/u1123114/Documents/projects/kinbank/parabank/env/lib/python3.9/site-packages/pip (python 3.9)
```
So I am confused as to why cldfbench cannot find pip. 

I followed the error trace to these lines in cldfbench util.py:
https://github.com/cldf/cldfbench/blob/b7013f37737532f09dd2f98d7a87f5992d96f01c/src/cldfbench/util.py#L30

If I change `pip` to `pip3` I can get past the error. 

In my global environment I don't have `pip` installed (only `pip3`). So, I wondered if something is happening whereby cldfbench is calling the global environment and not using the virtual environment for some reason?

**Comment by SamPassmore** [comment]
Never mind! 
I had not turned the virtual environment on, which was the important and decisive step.

**Comment by xrotwang** [comment]
Haven't seen this before, but I'd say this is a cldfbench bug. The
assumptions about the python installation seen to be too naive.

SamPassmore ***@***.***> schrieb am Mi., 5. Okt. 2022, 08:05:

**Comment by xrotwang** [comment]
I think it's still a bug. We shouldn't rely on the venv to be active, but
try to figure it out from the python interpreter.

SamPassmore ***@***.***> schrieb am Mi., 5. Okt. 2022, 08:13:

**Comment by xrotwang** [comment]
We should look for `pip` and `pip3` (in order) relative to `sys.executable`.
