### ISSUE TITLE
Python 3.6 is no longer available for GH actions

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldfbench#85]
It seems as if Python 3.6 is no longer available for GitHub actions:

https://github.com/cldf/cldfbench/blob/aaa4ea9aeeeee63ba7f7c2d2ff107de74f721b22/src/cldfbench/dataset_template/.github/workflows/python-package.yml#L15

Although it is still [listed](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) in the list of available Python version, GH actions fail with `3.6`. Newer versions (I've tested with `3.8.16`) are working correctly.

**Comment by xrotwang** [comment]
ah, yes. This must be upgraded to `"3.10"` I'd say.

**Comment by johenglisch** [comment]
Reminder to myself, and everybody, that those quotation marks need to be there, otherwise the yaml parser will interpret `3.10` as a decimal fraction and chop off the trailing `0` (happened to me more than once (<\_<)" ).
