### ISSUE TITLE
Issues with cldf-glottolog relation on Windows 

### ISSUE THREAD

**Issue by PromiseDodzi** [cldf/cldfbench#89]
We have been trying to initialize cldf-glottolog so we can run a script, without success. This is the command we ran on the terminal:

`cldfbench lexibank.makecldf lexibank_ourdataset.py --glottolog=ourpathto\Glottolog --glottolog-version=v4.8`

(where our dataset and our path are replaced by our specific project and path)

 We repeatedly get the following response on the terminal: 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Scripts\cldfbench.exe\__main__.py", line 7, in <module>
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\cldfbench\__main__.py", line 73, in main
    stack.enter_context(
  File "C:\Users\Melod\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 505, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\cldfcatalog\catalog.py", line 71, in __enter__
    self.checkout(self.tag)
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\cldfcatalog\repository.py", line 129, in checkout
    return self.repo.git.checkout(spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\git\cmd.py", line 739, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\git\cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\OneDrive\Documents\GitHub\heathdogon\venv\Lib\site-packages\git\cmd.py", line 1110, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout v4.8
  stderr: 'error: The following untracked working tree files would be overwritten by checkout:
        .gitattributes
        .gitignore
        .zenodo.json
        CHANGES.md
        CONTRIBUTING.md
        CONTRIBUTORS.md
        LICENSE
        MANIFEST.in
        README.md
        RELEASING.md
        SOURCES.md
        config/README.md
        config/aes_sources.ini
        config/aes_status.ini
        config/document_types.ini
        config/editors.ini
        config/language_types.ini
        config/languoid_levels.ini
        config/macroareas.ini
        config/macroareas/voronoi/africa.geojson
        config/macroareas/voronoi/australia.geojson
        config/macroareas/voronoi/eurasia.geojson
        config/macroareas/voronoi/north_america.geojson
        config/macroareas/voronoi/papunesia.geojson
        config/macroareas/voronoi/south_america.geojson
        config/med_types.ini
        config/publication.ini
        faq.md
        languoids/README.md
        languoids/dialects.md
        languoids/dialects_3.md
        languoids/dialects_a.md
        languoids/dialects_b.md
        languoids/dialects_c.md
        languoids/dialects_d.md
        languoids/dialects_e.md
        languoids/dialects_f.md
        languoids/dialects_g.md
        languoids/dialects_h.md
        languoids/dialects_i.md
        languoids/dialects_j.md
        languoids/dialects_k.md
        languoids/dialects_l.md
        languoids/dialects_m.md
        languoids/dialects_n.md
        languoids/dialects_o.md
        languoids/dialects_p.md
        languoids/dialects_q.md
        languoids/dialects_r.md
        languoids/dialects_s.md
        languoids/dialects_t.md
        languoids/dialects_u.md
        languoids/dialects_v.md
        languoids/dialects_w.md
        languoids/dialects_x.md
        languoids/dialects_y.md
        languoids/dialects_z.md
        languoids/families.md
        languoids/families_a.md
        languoids/families_b.md
        languoids/families_c.md
        languoids/families_d.md
        languoids/families_e.md
        languoids/families_f.md
        languoids/families_g.md
        languoids/families_h.md
        languoids/families_i.md
        languoids/families_j.md
        languoids/families_k.md
        languoids/families_l.md
        languoids/families_m.md
        languoids/families_n.md
        languoids/families_o.md
        languoids/families_p.md
        languoids/families_q.md
        languoids/families_r.md
        languoids/families_s.md
        languoids/families_t.md
        languoids/families_u.md
        languoids/families_v.md
        languoids/families_w.md
        languoids/families_x.md
        languoids/families_y.md
        languoids/families_z.md
        languoids/glottocodes.json
        languoids/languages.md
        languoids/languages_a.md
        languoids/languages_b.md
        languoids/languages_c.md
        languoids/languages_d.md
        languoids/languages_e.md
        languoids/languages_f.md
        languoids/languages_g.md
        languoids/languages_h.md
        languoids/languages_i.md
        languoids/languages_j.md
        languoids/languages_k.md
        languoids/languages_l.md
        languoids/languages_m.md
        languoids/languages_n.md
        languoids/languages_o.md
        languoids/languages_p.md
        languoids/languages_q.md
        languoids/languages_r.md
        languoids/languages_s.md
        languoids/languages_t.md
        languoids/languages_u.md
        languoids/languages_v.md
        languoids/languages_w.md
        languoids/languages_x.md
        languoids/languages_y.md
        languoids/languages_z.md
        languoids/superseded.csv
        languoids/tree/abin1243/md.ini
        languoids/tree/abis1238/md.ini
        languoids/tree/abkh1242/abkh1243/abaz1241/ashk1247/md.ini
        languoids/tree/abkh1242/abkh1243/abaz1241/bezs1238/md.ini
        languoids/tree/abkh1242/abkh1243/abaz1241/md.ini
        languoids/tree/abkh1242/abkh1243/abaz1241/tapa1256/md.ini
        languoids/tree/abkh1242/abkh1243/abkh1244/abzh1238/md.ini
        languoids/tree/abkh1242/abkh1243/abkh1244/bzyb1238/md.ini
        languoids/tree/abkh1242/abkh1243/abkh1244/md.ini
        languoids/tree/abkh1242/abkh1243/abkh1244/samu1242/md.ini
        languoids/tree/abkh1242/abkh1243/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/abad1240/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/bezh1247/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/natu1243/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/shap1240/md.ini
        languoids/tree/abkh1242/circ1239/adyg1241/xaku1238/md.ini
        languoids/tree/abkh1242/circ1239/kaba1278/grea1271/md.ini
        languoids/tree/abkh1242/circ1239/kaba1278/md.ini
        languoids/tree/abkh1242/circ1239/md.ini
        languoids/tree/abkh1242/md.ini
        languoids/tree/abkh1242/ubyk1235/md.ini
        languoids/tree/abun1252/abun1254
error: The following untracked working tree files would be removed by checkout:
        languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/unun9927/bafo1235/md.ini
        languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/cent2260/nort3376/inne1246/unun9927/md.ini

We are quite new with the package and try as we may, we just can't seem to fix the issue. Will anyone be able to help us with a quick fix?

**Comment by xrotwang** [comment]
You may want to try without the --glottolog-version option. It looks like
you work with a download of a certain Glottolog data release rather than a
git clone of Glottolog.

Promise ***@***.***> schrieb am Di., 12. Sep. 2023, 16:36:

**Comment by PromiseDodzi** [comment]
Thanks so much for the response. 
We cloned the glottolog version we were using. We however realized that during cloning, there were issues as some files could not be saved due to lengthy path names. We thus used the ``git clone -c core.longpaths=true url`` solution which helped us resolve that issue. After resolving that however, a new issue has popped up, and this is what is returned on the terminal after we run the command:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Scripts\cldfbench.exe\__main__.py", line 7, in <module>
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\cldfbench\__main__.py", line 89, in main
    return args.main(args) or 0
           ^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\pylexibank\commands\makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\cldfbench\cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\pylexibank\dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\cldfbench\dataset.py", line 206, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "C:\Users\Melod\PycharmProjects\pythonProject\heathdogon\lexibank_heathdogon.py", line 81, in cmd_makecldf
    args.writer.add_languages()
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\pylexibank\cldf.py", line 320, in add_languages
    self.add_language(**kw)
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\pylexibank\cldf.py", line 279, in add_language
    and kw['Glottocode'] in self.args.glottolog.api.cached_languoids:
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\clldutils\misc.py", line 241, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\cldfbench\catalogs.py", line 30, in cached_languoids
    return {lang.id: lang for lang in self.languoids()}
                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\cldfbench\catalogs.py", line 24, in languoids
    self.__languoids = list(super().languoids())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Melod\PycharmProjects\pythonProject\venv\Lib\site-packages\pyglottolog\api.py", line 267, in languoids
    or ((not is_max_level_int) and lang.level <= maxlevel):
                                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'LanguoidLevel'

**Comment by xrotwang** [comment]
So it seems you had run into the Windows path length limitation problem. It may be worth removing this limitation on your machine (see https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) because otherwise, working with the deeply nested Glottolog file hierarchy may always be error prone.

**Comment by LinguList** [comment]
BTW: as you show us full user paths in the error messages, it does not hurt, if you write full concrete commands that lead to the errors.
